name: Lazarus
version: 1.1.3
main: me.qiooip.lazarus.Lazarus
author: qIooIp

loadbefore:
- ShopGUIPlus

softdepend:
- AquaCore
- AtomAPI
- Chronium
- CoreAPI
- Core
- GroupManager
- Hestia
- LuckPerms
- mCore
- MizuAPI
- NCore
- PermissionsEx
- PowerfulPerms
- Spark
- UltraPermissions
- Zoom
- Zoot
- zPermissions
- Vault
- ViaVersion
- ProtocolSupport
- MineIsland
- LunarClientAPI